### ISSUE TITLE
Move to EzXML.jl

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaCloud/AWSCore.jl#105]
[XMLDict.jl](https://github.com/JuliaCloud/XMLDict.jl) has not been updated since 2018-09-20, we should probably move to a more popular package such as [EzXML.jl](https://github.com/bicycle1885/EzXML.jl)

**Comment by mattBrzezinski** [comment]
Usages:

- https://github.com/JuliaCloud/AWSCore.jl/blob/c4d9b3ff6fbb91077da39ff112eca384c552e7b1/src/AWSCore.jl#L517
- https://github.com/JuliaCloud/AWSCore.jl/blob/602ccdb0582866074ac76f72a9031066ea008ae5/src/AWSException.jl#L45
- https://github.com/JuliaCloud/AWSCore.jl/blob/602ccdb0582866074ac76f72a9031066ea008ae5/test/xml.jl#L19

**Comment by iamed2** [comment]
Since this is returned to the user, this would be a breaking change. But I'm for it, due to the inconsistent behaviour of XMLDicts with list-of-one scenarios.

**Comment by mattBrzezinski** [comment]
Closing this because `v2` will live in the [AWS.jl](https://github.com/JuliaCloud/AWS.jl) package.
