### ISSUE TITLE
Define request functions

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaCloud/AWSCore.jl#110]
## Overview
We will need functions to make requests for each type:

- [ ] `rest-xml`
- [ ] `rest-json`
- [ ] `json`
- [ ] `query`

We should use multiple dispatch on a `request type` struct for these functions.

**Comment by mattBrzezinski** [comment]
Closing this because `v2` will live in the [AWS.jl](https://github.com/JuliaCloud/AWS.jl) package.

**Comment by iamed2** [comment]
I thought this would be something that would live in AWSCore still. I guess this was not super clear in the design doc.
