### ISSUE TITLE
 HTTP/HTTPS Proxy Support for AWSCore.Services.email

### ISSUE THREAD

**Issue by saithejareddy** [JuliaCloud/AWSCore.jl#136]
Hi,

We are trying to use HTTP/HTTPS Proxy to communicate with SES. Is there a way to do this?

AWS SDK CLI will support HTTP/HTTPS Proxy Env variables. Is there a way to achieve this in AWSCore Library as well?

**Comment by mattBrzezinski** [comment]
This package uses [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl) to make requests. This package respects the `HTTP_PROXY` ENVVAR.

Also this package is more-or-less archived, I would suggest using [AWS.jl](https://github.com/JuliaCloud/AWS.jl).

**Comment by saithejareddy** [comment]
Thanks @mattBrzezinski .
We are using upper case HTTP env variables which were not supported by the HTTP.jl stable version from Package manager. For now we changed to lower case env variables which fixed the issue.
