### ISSUE TITLE
Add support to AWS Timestream

### ISSUE THREAD

**Issue by klangner** [JuliaCloud/AWSCore.jl#140]
Hello,
I'm looking for Julia library for accessing AWS Timestream database:
https://docs.aws.amazon.com/timestream/latest/developerguide/what-is-timestream.html

Should this be added to this package? Or somewhere else?
If to this package I might be interested in implementing. If not should I create new package for it?

**Comment by iamed2** [comment]
[timestream_query](https://juliacloud.github.io/AWS.jl/stable/services/timestream_query.html) and [timestream_write](https://juliacloud.github.io/AWS.jl/stable/services/timestream_write.html) APIs are available in [AWS.jl](https://github.com/JuliaCloud/AWS.jl)
