### ISSUE TITLE
add support for the AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaCloud/AWSCore.jl#15]
For choosing among multiple profiles in credentials file, described in [this](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/) AWS Security Blog post.

**Comment by samoconnor** [comment]
Hi @josefsachsconning,
The [`dot_aws_credentials()` function](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/AWSCredentials.jl#L262) supports the `AWS_DEFAULT_PROFILE` environment variable.

The [AWSCore-Configuration](https://juliacloud.github.io/AWSCore.jl/build/index.html#AWSCore-Configuration-1) section of the manual says:
> _aws_config understands the following [AWS CLI environment variables](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html): AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, AWS_DEFAULT_REGION, AWS_DEFAULT_PROFILE and AWS_CONFIG_FILE._

Hang on, that's odd, in the linked documentation has changed (`AWS_DEFAULT_PROFILE` to `AWS_PROFILE`).

Explanation: https://github.com/boto/boto/issues/3287

Fix here: https://github.com/JuliaCloud/AWSCore.jl/commit/23672b0396295300aa1e680efc623c20f43379cc
