### ISSUE TITLE
Use of http protocol by default

### ISSUE THREAD

**Issue by aviks** [JuliaCloud/AWSCore.jl#18]
This system of packages seem to use `http` as the default, going by : https://github.com/JuliaCloud/AWSCore.jl/blob/df1216674082eeecd2a511599820c924f5c7ca3d/src/names.jl#L27

This causes issues in certain cases with S3: 

```
ERROR: LoadError: InvalidArgument -- Requests specifying Server Side Encryption with AWS KMS managed keys must be made over a secure connection.

HTTP 400 -- GET http://my-bucket-name.s3.amazonaws.com/some/path/some_file.csv
 -- <?xml version="1.0" encoding="UTF-8"?>

<Error><Code>InvalidArgument</Code>
<Message>Requests specifying Server Side Encryption with AWS KMS managed keys must be made over a secure connection.</Message>
<ArgumentName>x-amz-server-side-encryption</ArgumentName>
<ArgumentValue>null</ArgumentValue>
<RequestId>ABCD1234</RequestId><HostId>ABCDEF12345678=</HostId>
</Error>
```

Isn't it safer to default all communication over https? Is there are workaround for this on the current codebase?

**Comment by aviks** [comment]
Hi @samoconnor is there any repercussion to changing this to `https` by default?

**Comment by samoconnor** [comment]
Hi @aviks, the `service_url` function uses https exclusively: https://github.com/JuliaCloud/AWSCore.jl/blob/e2479a7f959de96d76938e5d8b35db6c036362f8/src/AWSCore.jl#L201

If you "Call AWSCore/Services.jl functions directly", or "Use the low-level AWSSDK wrappers" as described in [README.md](https://github.com/JuliaCloud/AWSCore.jl/blob/ad2014b79436cadc4f49985e00b82ea9f434aa3b/README.md) the `service_url` function should be used and you should get https.

The AWSS3.jl package still calls the old `aws_endpoint` function, which uses http by default: https://github.com/samoconnor/AWSS3.jl/blob/74d20bb509f2806e848356766bbb58273fbd301d/src/AWSS3.jl#L90

AWS3.jl accepts a `:endpoint` entry in the config Dict, so you could override it that way: https://github.com/samoconnor/AWSS3.jl/blob/74d20bb509f2806e848356766bbb58273fbd301d/src/AWSS3.jl#L91

At this point, I think https by default is probably fine. There is some performance overhead, and in some use cases this may be significant. In many use cases I've worked with the data is encrypted anyway, so transport layer encryption is redundant. I think I'll switch to https by default and add an option `:use_http`.

**Comment by samoconnor** [comment]
https is now the default for AWSS3.jl:
https://github.com/samoconnor/AWSS3.jl/blob/dd9f7c0a9cbe6416631f1f239d338ce9c13be927/src/AWSS3.jl#L94
