### ISSUE TITLE
duplicate of HTTP.jl ?

### ISSUE THREAD

**Issue by jingpengw** [JuliaCloud/AWSCore.jl#19]
@samoconnor You have added a `vendor` folder and copied the HTTP.jl staff, isn't that a duplication?
```
WARNING: Method definition (::Type{String})(Base.SubArray{UInt8, 1, P, I, L} where L where I where P) in module HTTP at /usr/people/jingpeng/.julia/v0.6/AWSCore/src/vendor/HTTP.jl/compat.jl:37 overwritten in module HTTP at /usr/people/jingpeng/.julia/v0.6/HTTP/src/compat.jl:42.
```

**Comment by samoconnor** [comment]
Sorry, AWSCore is not compatible with latest HTTP.jl master. I'll remove AWSCore/src/vendor/HTTP.jl from AWSCore later today...

**Comment by jingpengw** [comment]
OK, thanks for the instant response!

**Comment by samoconnor** [comment]
Hi @jingpengw, I've just committed to AWSCore.jl and AWSS3.jl. Both should work with latest HTTP.jl master now (warning: tests pass, but no extensive real-world use yet).

**Comment by jingpengw** [comment]
@samoconnor  thanks! The tests of my code also passed.
