### ISSUE TITLE
Fix CI to allow tests to run on branches

### ISSUE THREAD

**Issue by morris25** [JuliaCloud/AWSCore.jl#54]
Currently if you make a branch off master, the CI tests will fail due to credential issues as seen here https://travis-ci.com/invenia/AWSCore.jl/jobs/168995448.

I'll note that the failing branch is identical to the current master.

**Comment by omus** [comment]
Fixed with: https://github.com/JuliaCloud/AWSCore.jl/pull/58

**Comment by notriddle** [comment]
All of the pull requests are getting failure status from Travis.

![](https://user-images.githubusercontent.com/1593513/52091519-e8df6f00-2571-11e9-9632-a36e826ec1b1.png)

**Comment by iamed2** [comment]
Yes, this was done.
