### ISSUE TITLE
InvalidSignatureException not retrying

### ISSUE THREAD

**Issue by morris25** [JuliaCloud/AWSCore.jl#74]
Recently I have been getting:
```julia
[warn | CloudWatchLogs]: InvalidSignatureException -- AWSException
HTTP.ExceptionRequest.StatusError(400, HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
x-amzn-RequestId: 86af99a0-5c68-11e9-9ca9-b5781024a1e7
Content-Type: application/x-amz-json-1.1
Content-Length: 151
Date: Thu, 11 Apr 2019 14:46:01 GMT
Connection: close

{
    "__type": "InvalidSignatureException",
    "message": "Signature expired: 20190411T144043Z is now earlier than 20190411T144101Z (20190411T144601Z - 5 min.)"
}
""")
```
This error should be caught and retried in `do_request`, but there seems to be a failure parsing the `StatusError`.

**Comment by iamed2** [comment]
How do you know it wasn't retried and then this was the final result?

**Comment by morris25** [comment]
I made a branch with debugging statements in the retry block, and checked what was caught against what was retried.

**Comment by iamed2** [comment]
Ah, found it!!
https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/AWSException.jl#L53
"message" is lowercase in the HTTP response but the parsing code looks for "Message".
