### ISSUE TITLE
AWS Account Number not returned properly

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaCloud/AWSCore.jl#87]
> https://github.com/JuliaCloud/AWSCore.jl/blob/v0.6.2/src/AWSCredentials.jl#L220

When the `creds.account_number` from the `AWSConfig` is an empty string, we are instead returning the user ARN.

This doesn't seem correct.

**Comment by omus** [comment]
That function call populates the user ARN and the account number and doesn't return the ARN ever (*phew*).

The code however is confusing and at least deserves a comment but I would recommend making a new function that just does the populating:

``` 
function _populate!(creds::AWSCredentials)
    r = Services.sts(aws, "GetCallerIdentity", [])
    creds.user_arn = r["Arn"]
    creds.account_number = r["Account"]
    return creds
end

function aws_user_arn(aws::AWSConfig)
    creds = aws[:creds]
    if creds.user_arn == ""
        _populate!(creds)
    end
    return creds.user_arn
end

function aws_account_number(aws::AWSConfig)
    creds = aws[:creds]
    if creds.account_number == ""
        _populate!(creds)
    end
    return creds.account_number
end
```

**Comment by mattBrzezinski** [comment]
Ah you're right, I miss read the `return` statement. I'll include this as part of my NFC CR coming up.
